using Azure2Pulumi.Importer.Common;
using Azure2Pulumi.Importer.DTOs;
using Azure2Pulumi.Importer.Helpers;
using Azure2Pulumi.Importer.Models;

namespace Azure2Pulumi.Importer.aadiam.DiagnosticSetting
{
	//This class has been auto-generated by voodoo and magic.
	internal class DiagnosticSetting : ImportResource
	{
		public override string AzureResourceType => "microsoft.aadiam/diagnosticSettings";
		protected override string PulumiResourceType => "azure-native:aadiam:DiagnosticSetting";
		protected override string DefaultTemplateResourceId => "/providers/microsoft.aadiam/diagnosticSettings/{name}";

		protected override Result<string> BuildPulumiImportId(AzureResource azureResource, Context context)
		{
			try
			{
			    var importResourceName = PulumiResourceHelper.GetNameIfNested(azureResource.Name);
				
				var importId = $"/providers/microsoft.aadiam/diagnosticSettings/{importResourceName}";
				return ResultBuilder.Success(importId);
			}
			catch (Exception)
			{
				var errorMessage = $"Unable to build ResourceId for resource {azureResource.Name} of type {AzureResourceType} | {PulumiResourceType}. Please find this resource in the import json and manually build the id based on the provided template.";
				return ResultBuilder.Failure<string>(errorMessage);
			}
		}
	}
}
