using Azure2Pulumi.Importer.Common;
using Azure2Pulumi.Importer.DTOs;
using Azure2Pulumi.Importer.Helpers;
using Azure2Pulumi.Importer.Models;

namespace Azure2Pulumi.Importer.connectedvmwarevsphere.VMInstanceGuestAgent
{
	//This class has been auto-generated by voodoo and magic.
	internal class VMInstanceGuestAgent : ImportResource
	{
		public override string AzureResourceType => "Microsoft.ConnectedVMwarevSphere/virtualMachineInstances/guestAgents";
		protected override string PulumiResourceType => "azure-native:connectedvmwarevsphere:VMInstanceGuestAgent";
		protected override string DefaultTemplateResourceId => "/{resourceUri}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachineInstances/default/guestAgents/default";

		protected override Result<string> BuildPulumiImportId(AzureResource azureResource, Context context)
		{
			try
			{
			    var importResourceName = PulumiResourceHelper.GetNameIfNested(azureResource.Name);
				
				var importId = $"/{importResourceName}/providers/Microsoft.ConnectedVMwarevSphere/virtualMachineInstances/default/guestAgents/default";
				return ResultBuilder.Success(importId);
			}
			catch (Exception)
			{
				var errorMessage = $"Unable to build ResourceId for resource {azureResource.Name} of type {AzureResourceType} | {PulumiResourceType}. Please find this resource in the import json and manually build the id based on the provided template.";
				return ResultBuilder.Failure<string>(errorMessage);
			}
		}
	}
}
