using Azure2Pulumi.Importer.Common;
using Azure2Pulumi.Importer.DTOs;
using Azure2Pulumi.Importer.Helpers;
using Azure2Pulumi.Importer.Models;

namespace Azure2Pulumi.Importer.management.HierarchySetting
{
	//This class has been auto-generated by voodoo and magic.
	internal class HierarchySetting : ImportResource
	{
		public override string AzureResourceType => "Microsoft.Management/managementGroups/settings";
		protected override string PulumiResourceType => "azure-native:management:HierarchySetting";
		protected override string DefaultTemplateResourceId => "/providers/Microsoft.Management/managementGroups/{groupId}/settings/default";

		protected override Result<string> BuildPulumiImportId(AzureResource azureResource, Context context)
		{
			try
			{
			    var importResourceName = PulumiResourceHelper.GetNameIfNested(azureResource.Name);
				
				var importId = $"/providers/Microsoft.Management/managementGroups/{importResourceName}/settings/default";
				return ResultBuilder.Success(importId);
			}
			catch (Exception)
			{
				var errorMessage = $"Unable to build ResourceId for resource {azureResource.Name} of type {AzureResourceType} | {PulumiResourceType}. Please find this resource in the import json and manually build the id based on the provided template.";
				return ResultBuilder.Failure<string>(errorMessage);
			}
		}
	}
}
