using Azure2Pulumi.Importer.Common;
using Azure2Pulumi.Importer.DTOs;
using Azure2Pulumi.Importer.Helpers;
using Azure2Pulumi.Importer.Models;

namespace Azure2Pulumi.Importer.portal.UserSettingsWithLocation
{
	//This class has been auto-generated by voodoo and magic.
	internal class UserSettingsWithLocation : ImportResource
	{
		public override string AzureResourceType => "Microsoft.Portal/locations/userSettings";
		protected override string PulumiResourceType => "azure-native:portal:UserSettingsWithLocation";
		protected override string DefaultTemplateResourceId => "/providers/Microsoft.Portal/locations/{location}/userSettings/{userSettingsName}";

        protected override Result<string> BuildPulumiImportId(AzureResource azureResource, Context context)
        {
            var errorMessage = $"Unable to build ResourceId for resource {azureResource.Name} of type {AzureResourceType} | {PulumiResourceType}. Please find this resource in the import json and manually build the id based on the provided template.";
            return ResultBuilder.Failure<string>(errorMessage);
        }
    }
}
